### ISSUE TITLE
Remove/uninstall

### ISSUE THREAD

**Issue by Drozt-md** [jamesdbailey/smartTBW#1]
Hi, is there any way to remove/uninstall smartTBW, i saw that u need xcode to "install" this but i dont have this. 

The installer work well, in the terminal with `ls -la /Application` I can see it (with no name just a dot (.) ).

Thanks for reading (sorry for bad english)

**Comment by jamesdbailey** [comment]
You don't need Xcode if you use the installer. It installs in /usr/local/bin as smartTBW. To get rid of it just use:

sudo rm /usr/local/bin/smartTBW

Type in your password as needed (no feedback on the password so type carefully).
